"""initial schema

Revision ID: 09ab38d8f260
Revises: 
Create Date: 2026-05-21 14:10:17.692965

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '09ab38d8f260'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=80), nullable=True),
    sa.Column('generated_by', sa.String(length=80), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('source_task_id', sa.String(length=48), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_format', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=80), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('execution_logs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=True),
    sa.Column('task_id', sa.String(length=48), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_level'), 'execution_logs', ['level'], unique=False)
    op.create_index(op.f('ix_execution_logs_task_id'), 'execution_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_execution_logs_timestamp'), 'execution_logs', ['timestamp'], unique=False)
    op.create_table('patient_cases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('primary_diagnosis_code', sa.String(length=50), nullable=True),
    sa.Column('primary_diagnosis_name', sa.String(length=200), nullable=True),
    sa.Column('secondary_diagnoses', sa.JSON(), nullable=True),
    sa.Column('primary_procedure_code', sa.String(length=50), nullable=True),
    sa.Column('primary_procedure_name', sa.String(length=200), nullable=True),
    sa.Column('other_procedures', sa.JSON(), nullable=True),
    sa.Column('discharge_type', sa.String(length=50), nullable=True),
    sa.Column('parse_result', sa.JSON(), nullable=True),
    sa.Column('parse_warnings', sa.JSON(), nullable=True),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_cases_created_at'), 'patient_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_cases_status'), 'patient_cases', ['status'], unique=False)
    op.create_table('rule_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('version_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_file_hash', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parse_errors', sa.JSON(), nullable=True),
    sa.Column('mdc_list', sa.JSON(), nullable=True),
    sa.Column('adrg_list', sa.JSON(), nullable=True),
    sa.Column('drg_list', sa.JSON(), nullable=True),
    sa.Column('mcc_list', sa.JSON(), nullable=True),
    sa.Column('cc_list', sa.JSON(), nullable=True),
    sa.Column('exclusion_table', sa.JSON(), nullable=True),
    sa.Column('rule_counts', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_versions_status'), 'rule_versions', ['status'], unique=False)
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm_config', sa.JSON(), nullable=True),
    sa.Column('storage_config', sa.JSON(), nullable=True),
    sa.Column('active_rule_version_id', sa.String(length=40), nullable=True),
    sa.Column('demo_initialized', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_tasks',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('template', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_doc_id', sa.String(length=40), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['result_doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_tasks_created_at'), 'document_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_tasks_status'), 'document_tasks', ['status'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('content_snapshot', sa.Text(), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('grouping_tasks',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('rule_version_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['patient_cases.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grouping_tasks_case_id'), 'grouping_tasks', ['case_id'], unique=False)
    op.create_index(op.f('ix_grouping_tasks_created_at'), 'grouping_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_grouping_tasks_rule_version_id'), 'grouping_tasks', ['rule_version_id'], unique=False)
    op.create_index(op.f('ix_grouping_tasks_status'), 'grouping_tasks', ['status'], unique=False)
    op.create_table('test_tasks',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('rule_version_id', sa.String(length=40), nullable=True),
    sa.Column('scenario_types', sa.JSON(), nullable=True),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('sample_case_ids', sa.JSON(), nullable=True),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_tasks_created_at'), 'test_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_tasks_status'), 'test_tasks', ['status'], unique=False)
    op.create_table('grouping_results',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=48), nullable=False),
    sa.Column('mdc_code', sa.String(length=20), nullable=True),
    sa.Column('mdc_name', sa.String(length=200), nullable=True),
    sa.Column('adrg_code', sa.String(length=20), nullable=True),
    sa.Column('adrg_name', sa.String(length=200), nullable=True),
    sa.Column('drg_code', sa.String(length=20), nullable=True),
    sa.Column('drg_name', sa.String(length=200), nullable=True),
    sa.Column('is_grouped', sa.Boolean(), nullable=False),
    sa.Column('ungrouped_reason', sa.Text(), nullable=True),
    sa.Column('complication', sa.String(length=10), nullable=True),
    sa.Column('evidence_chain', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('candidate_rules', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['grouping_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index(op.f('ix_grouping_results_drg_code'), 'grouping_results', ['drg_code'], unique=False)
    op.create_table('task_steps',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=48), nullable=False),
    sa.Column('step_name', sa.String(length=40), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['grouping_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_steps_task_id'), 'task_steps', ['task_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('test_task_id', sa.String(length=48), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scenario_type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('requirement_ref', sa.String(length=40), nullable=True),
    sa.Column('rule_version_id', sa.String(length=40), nullable=True),
    sa.Column('input_case', sa.JSON(), nullable=True),
    sa.Column('expected_result', sa.JSON(), nullable=True),
    sa.Column('expected_explanation', sa.Text(), nullable=True),
    sa.Column('actual_result', sa.JSON(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.ForeignKeyConstraint(['test_task_id'], ['test_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_requirement_ref'), 'test_cases', ['requirement_ref'], unique=False)
    op.create_index(op.f('ix_test_cases_scenario_type'), 'test_cases', ['scenario_type'], unique=False)
    op.create_index(op.f('ix_test_cases_test_task_id'), 'test_cases', ['test_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_cases_test_task_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_scenario_type'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_requirement_ref'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_task_steps_task_id'), table_name='task_steps')
    op.drop_table('task_steps')
    op.drop_index(op.f('ix_grouping_results_drg_code'), table_name='grouping_results')
    op.drop_table('grouping_results')
    op.drop_index(op.f('ix_test_tasks_status'), table_name='test_tasks')
    op.drop_index(op.f('ix_test_tasks_created_at'), table_name='test_tasks')
    op.drop_table('test_tasks')
    op.drop_index(op.f('ix_grouping_tasks_status'), table_name='grouping_tasks')
    op.drop_index(op.f('ix_grouping_tasks_rule_version_id'), table_name='grouping_tasks')
    op.drop_index(op.f('ix_grouping_tasks_created_at'), table_name='grouping_tasks')
    op.drop_index(op.f('ix_grouping_tasks_case_id'), table_name='grouping_tasks')
    op.drop_table('grouping_tasks')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_tasks_status'), table_name='document_tasks')
    op.drop_index(op.f('ix_document_tasks_created_at'), table_name='document_tasks')
    op.drop_table('document_tasks')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_rule_versions_status'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_patient_cases_status'), table_name='patient_cases')
    op.drop_index(op.f('ix_patient_cases_created_at'), table_name='patient_cases')
    op.drop_table('patient_cases')
    op.drop_index(op.f('ix_execution_logs_timestamp'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_task_id'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_level'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
